name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build slides
      run: |
        jupyter nbconvert notebook.ipynb --to slides --reveal-prefix reveal.js
        mv notebook.slides.html index.html
        
    - name: Push to main
      run: |
          git config --global user.name 'CI'
          git config --global user.email 'CI@example.com'
          git add index.html
          git commit --allow-empty -m "[CI] Automatic publish slides to GitHub Pages"
          git push
